# Generated by Django 4.1.4 on 2022-12-18 20:20

from django.db import migrations, models
import djongo.models.fields
import research_extractor.api_aggregator.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Results",
            fields=[
                (
                    "title",
                    models.CharField(
                        max_length=1000, primary_key=True, serialize=False
                    ),
                ),
                ("author", models.CharField(max_length=1000)),
                ("article_date", models.CharField(max_length=1000)),
                (
                    "publication_name",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("issn", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "affiliation_name",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                (
                    "affiliation_country",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("abstract", models.CharField(blank=True, max_length=10000, null=True)),
                ("url", models.CharField(max_length=1000)),
                ("liked", models.BooleanField(default=False)),
            ],
            options={"managed": False,},
        ),
        migrations.CreateModel(
            name="SearchResults",
            fields=[
                ("search_id", models.AutoField(primary_key=True, serialize=False)),
                ("search_name", models.CharField(max_length=10000)),
                ("research_db", models.CharField(max_length=50)),
                (
                    "results",
                    djongo.models.fields.ArrayField(
                        model_container=research_extractor.api_aggregator.models.Results
                    ),
                ),
            ],
        ),
    ]
